// Generated by CoffeeScript 1.7.1
(function() {
  var Bear, app, bodyParser, express, mongoose, port, router;

  require('coffee-script/register');

  express = require('express');

  app = express();

  bodyParser = require('body-parser');

  mongoose = require('mongoose');

  mongoose.connect('YOUR_MONGO_URI');

  Bear = require('./app/models/bear');

  app.use(bodyParser());

  port = process.env.PORT || 8080;

  router = express.Router();

  router.use(function(req, res, next) {
    console.log('Stuff is happening');
    return next();
  });

  router.get('/', function(req, res) {
    return res.json({
      message: 'welcome to the app'
    });
  });

  router.route('/bears').post(function(req, res) {
    var bear;
    bear = new Bear();
    bear.name = req.body.name;
    return bear.save(function(err) {
      if (err) {
        res.send(err);
      }
      return res.json({
        message: 'Bear created'
      });
    });
  }).get(function(req, res) {
    return Bear.find(function(err, bears) {
      if (err) {
        res.send(err);
      }
      return res.json(bears);
    });
  });

  router.route('/bears/:bear_id').get(function(req, res) {
    return Bear.findById(req.params.bear_id, function(err, bear) {
      if (err) {
        res.send(err);
      }
      return res.json(bear);
    });
  }).put(function(req, res) {
    return Bear.findById(req.params.bear_id, function(err, bear) {
      if (err) {
        res.send(err);
      }
      bear.name = req.body.name;
      return bear.save(function(err) {
        if (err) {
          res.send(err);
        }
        return res.json({
          message: 'Bear updated'
        });
      });
    });
  })["delete"](function(req, res) {
    return Bear.remove({
      _id: req.params.bear_id
    }, function(err, bear) {
      if (err) {
        res.send(err);
      }
      return res.json({
        message: 'Successfully deleted'
      });
    });
  });

  app.use('/api', router);

  app.listen(port);

  console.log('Go to port ' + port);

}).call(this);
